### ISSUE TITLE
Add RJ12 RS232 to USB Cable to Amazon Parts List

### ISSUE THREAD

**Issue by jim0020** [corbinbs/solarshed#21]
Add this special RJ12 RS232 to USB cable which is specific to the Renogy Rover to the Amazon parts list.

[https://www.amazon.com/Charger-Controller-Converter-Adapter-Chipset/dp/B07JGRJR4V/ref=sr_1_1?dib=eyJ2IjoiMSJ9.YJO2BrzCsplwCiMdfk71YTPZmm32o59VwQAvyDH4Bhg.xr1lqJ3pMqsC-pmM-gOKnkkdaDe7PciwK2uI8dBMVPA&dib_tag=se&keywords=Suamdoen+SRNE+ML2430+Solar+Charger+Cable+MPPT+Solar+Charger+Controller+USB+RS232+Serial+6P6C+Converter+Adapter+Cable+6ft+with+FTDI+Chipset+Support+for+Win+7%2F8%2F10%2FXP%2FAndroid%2FMac%2FLinux%2Fetc&qid=1705444944&sr=8-1](url)

**Comment by corbinbs** [comment]
thanks @jim0020 !   I added it to the parts list.   Appreciate it!
